package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * AllarmiStatoImpiantoId generated by hbm2java
 */
public class AllarmiStatoImpiantoId implements java.io.Serializable {

	private Byte statoInterrMagnetotermico;
	private Byte statoDifferenzialeApparato;
	private Byte statoOnOff;
	private Byte assenzaReteElettrica;
	private Byte mancatoOnTramonto;
	private Byte mancatoOffAlba;
	private Integer assorbimentoSopraSoglia;
	private Integer assorbimentoSottoSoglia;
	private Byte aperturaQuadroElettrico;
	private Byte allarmeGuastoSingoloPunto;

	public AllarmiStatoImpiantoId() {
	}

	public AllarmiStatoImpiantoId(Byte statoInterrMagnetotermico,
			Byte statoDifferenzialeApparato, Byte statoOnOff,
			Byte assenzaReteElettrica, Byte mancatoOnTramonto,
			Byte mancatoOffAlba, Integer assorbimentoSopraSoglia,
			Integer assorbimentoSottoSoglia, Byte aperturaQuadroElettrico,
			Byte allarmeGuastoSingoloPunto) {
		this.statoInterrMagnetotermico = statoInterrMagnetotermico;
		this.statoDifferenzialeApparato = statoDifferenzialeApparato;
		this.statoOnOff = statoOnOff;
		this.assenzaReteElettrica = assenzaReteElettrica;
		this.mancatoOnTramonto = mancatoOnTramonto;
		this.mancatoOffAlba = mancatoOffAlba;
		this.assorbimentoSopraSoglia = assorbimentoSopraSoglia;
		this.assorbimentoSottoSoglia = assorbimentoSottoSoglia;
		this.aperturaQuadroElettrico = aperturaQuadroElettrico;
		this.allarmeGuastoSingoloPunto = allarmeGuastoSingoloPunto;
	}

	public Byte getStatoInterrMagnetotermico() {
		return this.statoInterrMagnetotermico;
	}

	public void setStatoInterrMagnetotermico(Byte statoInterrMagnetotermico) {
		this.statoInterrMagnetotermico = statoInterrMagnetotermico;
	}

	public Byte getStatoDifferenzialeApparato() {
		return this.statoDifferenzialeApparato;
	}

	public void setStatoDifferenzialeApparato(Byte statoDifferenzialeApparato) {
		this.statoDifferenzialeApparato = statoDifferenzialeApparato;
	}

	public Byte getStatoOnOff() {
		return this.statoOnOff;
	}

	public void setStatoOnOff(Byte statoOnOff) {
		this.statoOnOff = statoOnOff;
	}

	public Byte getAssenzaReteElettrica() {
		return this.assenzaReteElettrica;
	}

	public void setAssenzaReteElettrica(Byte assenzaReteElettrica) {
		this.assenzaReteElettrica = assenzaReteElettrica;
	}

	public Byte getMancatoOnTramonto() {
		return this.mancatoOnTramonto;
	}

	public void setMancatoOnTramonto(Byte mancatoOnTramonto) {
		this.mancatoOnTramonto = mancatoOnTramonto;
	}

	public Byte getMancatoOffAlba() {
		return this.mancatoOffAlba;
	}

	public void setMancatoOffAlba(Byte mancatoOffAlba) {
		this.mancatoOffAlba = mancatoOffAlba;
	}

	public Integer getAssorbimentoSopraSoglia() {
		return this.assorbimentoSopraSoglia;
	}

	public void setAssorbimentoSopraSoglia(Integer assorbimentoSopraSoglia) {
		this.assorbimentoSopraSoglia = assorbimentoSopraSoglia;
	}

	public Integer getAssorbimentoSottoSoglia() {
		return this.assorbimentoSottoSoglia;
	}

	public void setAssorbimentoSottoSoglia(Integer assorbimentoSottoSoglia) {
		this.assorbimentoSottoSoglia = assorbimentoSottoSoglia;
	}

	public Byte getAperturaQuadroElettrico() {
		return this.aperturaQuadroElettrico;
	}

	public void setAperturaQuadroElettrico(Byte aperturaQuadroElettrico) {
		this.aperturaQuadroElettrico = aperturaQuadroElettrico;
	}

	public Byte getAllarmeGuastoSingoloPunto() {
		return this.allarmeGuastoSingoloPunto;
	}

	public void setAllarmeGuastoSingoloPunto(Byte allarmeGuastoSingoloPunto) {
		this.allarmeGuastoSingoloPunto = allarmeGuastoSingoloPunto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AllarmiStatoImpiantoId))
			return false;
		AllarmiStatoImpiantoId castOther = (AllarmiStatoImpiantoId) other;

		return ((this.getStatoInterrMagnetotermico() == castOther
				.getStatoInterrMagnetotermico()) || (this
				.getStatoInterrMagnetotermico() != null
				&& castOther.getStatoInterrMagnetotermico() != null && this
				.getStatoInterrMagnetotermico().equals(
						castOther.getStatoInterrMagnetotermico())))
				&& ((this.getStatoDifferenzialeApparato() == castOther
						.getStatoDifferenzialeApparato()) || (this
						.getStatoDifferenzialeApparato() != null
						&& castOther.getStatoDifferenzialeApparato() != null && this
						.getStatoDifferenzialeApparato().equals(
								castOther.getStatoDifferenzialeApparato())))
				&& ((this.getStatoOnOff() == castOther.getStatoOnOff()) || (this
						.getStatoOnOff() != null
						&& castOther.getStatoOnOff() != null && this
						.getStatoOnOff().equals(castOther.getStatoOnOff())))
				&& ((this.getAssenzaReteElettrica() == castOther
						.getAssenzaReteElettrica()) || (this
						.getAssenzaReteElettrica() != null
						&& castOther.getAssenzaReteElettrica() != null && this
						.getAssenzaReteElettrica().equals(
								castOther.getAssenzaReteElettrica())))
				&& ((this.getMancatoOnTramonto() == castOther
						.getMancatoOnTramonto()) || (this
						.getMancatoOnTramonto() != null
						&& castOther.getMancatoOnTramonto() != null && this
						.getMancatoOnTramonto().equals(
								castOther.getMancatoOnTramonto())))
				&& ((this.getMancatoOffAlba() == castOther.getMancatoOffAlba()) || (this
						.getMancatoOffAlba() != null
						&& castOther.getMancatoOffAlba() != null && this
						.getMancatoOffAlba().equals(
								castOther.getMancatoOffAlba())))
				&& ((this.getAssorbimentoSopraSoglia() == castOther
						.getAssorbimentoSopraSoglia()) || (this
						.getAssorbimentoSopraSoglia() != null
						&& castOther.getAssorbimentoSopraSoglia() != null && this
						.getAssorbimentoSopraSoglia().equals(
								castOther.getAssorbimentoSopraSoglia())))
				&& ((this.getAssorbimentoSottoSoglia() == castOther
						.getAssorbimentoSottoSoglia()) || (this
						.getAssorbimentoSottoSoglia() != null
						&& castOther.getAssorbimentoSottoSoglia() != null && this
						.getAssorbimentoSottoSoglia().equals(
								castOther.getAssorbimentoSottoSoglia())))
				&& ((this.getAperturaQuadroElettrico() == castOther
						.getAperturaQuadroElettrico()) || (this
						.getAperturaQuadroElettrico() != null
						&& castOther.getAperturaQuadroElettrico() != null && this
						.getAperturaQuadroElettrico().equals(
								castOther.getAperturaQuadroElettrico())))
				&& ((this.getAllarmeGuastoSingoloPunto() == castOther
						.getAllarmeGuastoSingoloPunto()) || (this
						.getAllarmeGuastoSingoloPunto() != null
						&& castOther.getAllarmeGuastoSingoloPunto() != null && this
						.getAllarmeGuastoSingoloPunto().equals(
								castOther.getAllarmeGuastoSingoloPunto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getStatoInterrMagnetotermico() == null ? 0 : this
						.getStatoInterrMagnetotermico().hashCode());
		result = 37
				* result
				+ (getStatoDifferenzialeApparato() == null ? 0 : this
						.getStatoDifferenzialeApparato().hashCode());
		result = 37
				* result
				+ (getStatoOnOff() == null ? 0 : this.getStatoOnOff()
						.hashCode());
		result = 37
				* result
				+ (getAssenzaReteElettrica() == null ? 0 : this
						.getAssenzaReteElettrica().hashCode());
		result = 37
				* result
				+ (getMancatoOnTramonto() == null ? 0 : this
						.getMancatoOnTramonto().hashCode());
		result = 37
				* result
				+ (getMancatoOffAlba() == null ? 0 : this.getMancatoOffAlba()
						.hashCode());
		result = 37
				* result
				+ (getAssorbimentoSopraSoglia() == null ? 0 : this
						.getAssorbimentoSopraSoglia().hashCode());
		result = 37
				* result
				+ (getAssorbimentoSottoSoglia() == null ? 0 : this
						.getAssorbimentoSottoSoglia().hashCode());
		result = 37
				* result
				+ (getAperturaQuadroElettrico() == null ? 0 : this
						.getAperturaQuadroElettrico().hashCode());
		result = 37
				* result
				+ (getAllarmeGuastoSingoloPunto() == null ? 0 : this
						.getAllarmeGuastoSingoloPunto().hashCode());
		return result;
	}

}
