package com.rigers.db;

// Generated 7-apr-2014 11.05.46 by Hibernate Tools 3.4.0.CR1

/**
 * AllarmiStatoImpianto generated by hbm2java
 */
public class AllarmiStatoImpianto implements java.io.Serializable {

	private AllarmiStatoImpiantoId id;
	private LetturaDispositivoPub letturaDispositivoPub;
	private Byte statoInterrMagnetotermico;
	private Byte statoDifferenzialeApparato;
	private Byte statoOnOff;
	private Byte assenzaReteElettrica;
	private Byte mancatoOnTramonto;
	private Byte mancatoOffAlba;
	private Integer assorbimentoSopraSoglia;
	private Integer assorbimentoSottoSoglia;
	private Byte aperturaQuadroElettrico;
	private Byte allarmeGuastoSingoloPunto;

	public AllarmiStatoImpianto() {
	}

	public AllarmiStatoImpianto(LetturaDispositivoPub letturaDispositivoPub) {
		this.letturaDispositivoPub = letturaDispositivoPub;
	}

	public AllarmiStatoImpianto(LetturaDispositivoPub letturaDispositivoPub,
			Byte statoInterrMagnetotermico, Byte statoDifferenzialeApparato,
			Byte statoOnOff, Byte assenzaReteElettrica, Byte mancatoOnTramonto,
			Byte mancatoOffAlba, Integer assorbimentoSopraSoglia,
			Integer assorbimentoSottoSoglia, Byte aperturaQuadroElettrico,
			Byte allarmeGuastoSingoloPunto) {
		this.letturaDispositivoPub = letturaDispositivoPub;
		this.statoInterrMagnetotermico = statoInterrMagnetotermico;
		this.statoDifferenzialeApparato = statoDifferenzialeApparato;
		this.statoOnOff = statoOnOff;
		this.assenzaReteElettrica = assenzaReteElettrica;
		this.mancatoOnTramonto = mancatoOnTramonto;
		this.mancatoOffAlba = mancatoOffAlba;
		this.assorbimentoSopraSoglia = assorbimentoSopraSoglia;
		this.assorbimentoSottoSoglia = assorbimentoSottoSoglia;
		this.aperturaQuadroElettrico = aperturaQuadroElettrico;
		this.allarmeGuastoSingoloPunto = allarmeGuastoSingoloPunto;
	}

	public AllarmiStatoImpiantoId getId() {
		return this.id;
	}

	public void setId(AllarmiStatoImpiantoId id) {
		this.id = id;
	}

	public LetturaDispositivoPub getLetturaDispositivoPub() {
		return this.letturaDispositivoPub;
	}

	public void setLetturaDispositivoPub(
			LetturaDispositivoPub letturaDispositivoPub) {
		this.letturaDispositivoPub = letturaDispositivoPub;
	}

	public Byte getStatoInterrMagnetotermico() {
		return this.statoInterrMagnetotermico;
	}

	public void setStatoInterrMagnetotermico(Byte statoInterrMagnetotermico) {
		this.statoInterrMagnetotermico = statoInterrMagnetotermico;
	}

	public Byte getStatoDifferenzialeApparato() {
		return this.statoDifferenzialeApparato;
	}

	public void setStatoDifferenzialeApparato(Byte statoDifferenzialeApparato) {
		this.statoDifferenzialeApparato = statoDifferenzialeApparato;
	}

	public Byte getStatoOnOff() {
		return this.statoOnOff;
	}

	public void setStatoOnOff(Byte statoOnOff) {
		this.statoOnOff = statoOnOff;
	}

	public Byte getAssenzaReteElettrica() {
		return this.assenzaReteElettrica;
	}

	public void setAssenzaReteElettrica(Byte assenzaReteElettrica) {
		this.assenzaReteElettrica = assenzaReteElettrica;
	}

	public Byte getMancatoOnTramonto() {
		return this.mancatoOnTramonto;
	}

	public void setMancatoOnTramonto(Byte mancatoOnTramonto) {
		this.mancatoOnTramonto = mancatoOnTramonto;
	}

	public Byte getMancatoOffAlba() {
		return this.mancatoOffAlba;
	}

	public void setMancatoOffAlba(Byte mancatoOffAlba) {
		this.mancatoOffAlba = mancatoOffAlba;
	}

	public Integer getAssorbimentoSopraSoglia() {
		return this.assorbimentoSopraSoglia;
	}

	public void setAssorbimentoSopraSoglia(Integer assorbimentoSopraSoglia) {
		this.assorbimentoSopraSoglia = assorbimentoSopraSoglia;
	}

	public Integer getAssorbimentoSottoSoglia() {
		return this.assorbimentoSottoSoglia;
	}

	public void setAssorbimentoSottoSoglia(Integer assorbimentoSottoSoglia) {
		this.assorbimentoSottoSoglia = assorbimentoSottoSoglia;
	}

	public Byte getAperturaQuadroElettrico() {
		return this.aperturaQuadroElettrico;
	}

	public void setAperturaQuadroElettrico(Byte aperturaQuadroElettrico) {
		this.aperturaQuadroElettrico = aperturaQuadroElettrico;
	}

	public Byte getAllarmeGuastoSingoloPunto() {
		return this.allarmeGuastoSingoloPunto;
	}

	public void setAllarmeGuastoSingoloPunto(Byte allarmeGuastoSingoloPunto) {
		this.allarmeGuastoSingoloPunto = allarmeGuastoSingoloPunto;
	}

}
