package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * AllarmiStatoImpianto generated by hbm2java
 */
public class AllarmiStatoImpianto implements java.io.Serializable {

	private AllarmiStatoImpiantoId id;

	public AllarmiStatoImpianto() {
	}

	public AllarmiStatoImpianto(AllarmiStatoImpiantoId id) {
		this.id = id;
	}

	public AllarmiStatoImpiantoId getId() {
		return this.id;
	}

	public void setId(AllarmiStatoImpiantoId id) {
		this.id = id;
	}

}
