package com.rigers.db;

// Generated 24-mar-2014 14.44.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DispositivoPub generated by hbm2java
 */
public class DispositivoPub implements java.io.Serializable {

	private DispositivoPubId id;
	private Compartimento compartimento;
	private String nomeDispositivo;
	private Set videosorveglianzas = new HashSet(0);
	private Set letturaDispositivoPubs = new HashSet(0);
	private IlluminazionePub illuminazionePub;

	public DispositivoPub() {
	}

	public DispositivoPub(DispositivoPubId id, Compartimento compartimento) {
		this.id = id;
		this.compartimento = compartimento;
	}

	public DispositivoPub(DispositivoPubId id, Compartimento compartimento,
			String nomeDispositivo, Set videosorveglianzas,
			Set letturaDispositivoPubs, IlluminazionePub illuminazionePub) {
		this.id = id;
		this.compartimento = compartimento;
		this.nomeDispositivo = nomeDispositivo;
		this.videosorveglianzas = videosorveglianzas;
		this.letturaDispositivoPubs = letturaDispositivoPubs;
		this.illuminazionePub = illuminazionePub;
	}

	public DispositivoPubId getId() {
		return this.id;
	}

	public void setId(DispositivoPubId id) {
		this.id = id;
	}

	public Compartimento getCompartimento() {
		return this.compartimento;
	}

	public void setCompartimento(Compartimento compartimento) {
		this.compartimento = compartimento;
	}

	public String getNomeDispositivo() {
		return this.nomeDispositivo;
	}

	public void setNomeDispositivo(String nomeDispositivo) {
		this.nomeDispositivo = nomeDispositivo;
	}

	public Set getVideosorveglianzas() {
		return this.videosorveglianzas;
	}

	public void setVideosorveglianzas(Set videosorveglianzas) {
		this.videosorveglianzas = videosorveglianzas;
	}

	public Set getLetturaDispositivoPubs() {
		return this.letturaDispositivoPubs;
	}

	public void setLetturaDispositivoPubs(Set letturaDispositivoPubs) {
		this.letturaDispositivoPubs = letturaDispositivoPubs;
	}

	public IlluminazionePub getIlluminazionePub() {
		return this.illuminazionePub;
	}

	public void setIlluminazionePub(IlluminazionePub illuminazionePub) {
		this.illuminazionePub = illuminazionePub;
	}

}
