package com.rigers.db;

// Generated 27-mar-2014 21.08.14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Dispositivo generated by hbm2java
 */
public class Dispositivo implements java.io.Serializable {

	private DispositivoId id;
	private Edificio edificio;
	private String nomeDispositivo;
	private Set letturaDispositivos = new HashSet(0);

	public Dispositivo() {
	}

	public Dispositivo(DispositivoId id, Edificio edificio) {
		this.id = id;
		this.edificio = edificio;
	}

	public Dispositivo(DispositivoId id, Edificio edificio,
			String nomeDispositivo, Set letturaDispositivos) {
		this.id = id;
		this.edificio = edificio;
		this.nomeDispositivo = nomeDispositivo;
		this.letturaDispositivos = letturaDispositivos;
	}

	public DispositivoId getId() {
		return this.id;
	}

	public void setId(DispositivoId id) {
		this.id = id;
	}

	public Edificio getEdificio() {
		return this.edificio;
	}

	public void setEdificio(Edificio edificio) {
		this.edificio = edificio;
	}

	public String getNomeDispositivo() {
		return this.nomeDispositivo;
	}

	public void setNomeDispositivo(String nomeDispositivo) {
		this.nomeDispositivo = nomeDispositivo;
	}

	public Set getLetturaDispositivos() {
		return this.letturaDispositivos;
	}

	public void setLetturaDispositivos(Set letturaDispositivos) {
		this.letturaDispositivos = letturaDispositivos;
	}

}
