package com.rigers.db;

// Generated 24-mar-2014 14.44.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Dispositivo generated by hbm2java
 */
public class Dispositivo implements java.io.Serializable {

	private DispositivoId id;
	private Edificio edificio;
	private String nomeDispositivo;
	private MeterElettrico meterElettrico;
	private MeterSonde meterSonde;
	private MeterGas meterGas;
	private MeterTermie meterTermie;
	private Set letturaDispositivos = new HashSet(0);
	private MeterAcqua meterAcqua;
	private MeterRipartitoreCalore meterRipartitoreCalore;

	public Dispositivo() {
	}

	public Dispositivo(DispositivoId id, Edificio edificio) {
		this.id = id;
		this.edificio = edificio;
	}

	public Dispositivo(DispositivoId id, Edificio edificio,
			String nomeDispositivo, MeterElettrico meterElettrico,
			MeterSonde meterSonde, MeterGas meterGas, MeterTermie meterTermie,
			Set letturaDispositivos, MeterAcqua meterAcqua,
			MeterRipartitoreCalore meterRipartitoreCalore) {
		this.id = id;
		this.edificio = edificio;
		this.nomeDispositivo = nomeDispositivo;
		this.meterElettrico = meterElettrico;
		this.meterSonde = meterSonde;
		this.meterGas = meterGas;
		this.meterTermie = meterTermie;
		this.letturaDispositivos = letturaDispositivos;
		this.meterAcqua = meterAcqua;
		this.meterRipartitoreCalore = meterRipartitoreCalore;
	}

	public DispositivoId getId() {
		return this.id;
	}

	public void setId(DispositivoId id) {
		this.id = id;
	}

	public Edificio getEdificio() {
		return this.edificio;
	}

	public void setEdificio(Edificio edificio) {
		this.edificio = edificio;
	}

	public String getNomeDispositivo() {
		return this.nomeDispositivo;
	}

	public void setNomeDispositivo(String nomeDispositivo) {
		this.nomeDispositivo = nomeDispositivo;
	}

	public MeterElettrico getMeterElettrico() {
		return this.meterElettrico;
	}

	public void setMeterElettrico(MeterElettrico meterElettrico) {
		this.meterElettrico = meterElettrico;
	}

	public MeterSonde getMeterSonde() {
		return this.meterSonde;
	}

	public void setMeterSonde(MeterSonde meterSonde) {
		this.meterSonde = meterSonde;
	}

	public MeterGas getMeterGas() {
		return this.meterGas;
	}

	public void setMeterGas(MeterGas meterGas) {
		this.meterGas = meterGas;
	}

	public MeterTermie getMeterTermie() {
		return this.meterTermie;
	}

	public void setMeterTermie(MeterTermie meterTermie) {
		this.meterTermie = meterTermie;
	}

	public Set getLetturaDispositivos() {
		return this.letturaDispositivos;
	}

	public void setLetturaDispositivos(Set letturaDispositivos) {
		this.letturaDispositivos = letturaDispositivos;
	}

	public MeterAcqua getMeterAcqua() {
		return this.meterAcqua;
	}

	public void setMeterAcqua(MeterAcqua meterAcqua) {
		this.meterAcqua = meterAcqua;
	}

	public MeterRipartitoreCalore getMeterRipartitoreCalore() {
		return this.meterRipartitoreCalore;
	}

	public void setMeterRipartitoreCalore(
			MeterRipartitoreCalore meterRipartitoreCalore) {
		this.meterRipartitoreCalore = meterRipartitoreCalore;
	}

}
