package com.rigers.db;

// Generated 27-mar-2014 21.08.14 by Hibernate Tools 3.4.0.CR1

/**
 * DispositivoPubId generated by hbm2java
 */
public class DispositivoPubId implements java.io.Serializable {

	private int idDispositivoPub;
	private int idCompartimento;

	public DispositivoPubId() {
	}

	public DispositivoPubId(int idDispositivoPub, int idCompartimento) {
		this.idDispositivoPub = idDispositivoPub;
		this.idCompartimento = idCompartimento;
	}

	public int getIdDispositivoPub() {
		return this.idDispositivoPub;
	}

	public void setIdDispositivoPub(int idDispositivoPub) {
		this.idDispositivoPub = idDispositivoPub;
	}

	public int getIdCompartimento() {
		return this.idCompartimento;
	}

	public void setIdCompartimento(int idCompartimento) {
		this.idCompartimento = idCompartimento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DispositivoPubId))
			return false;
		DispositivoPubId castOther = (DispositivoPubId) other;

		return (this.getIdDispositivoPub() == castOther.getIdDispositivoPub())
				&& (this.getIdCompartimento() == castOther.getIdCompartimento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDispositivoPub();
		result = 37 * result + this.getIdCompartimento();
		return result;
	}

}
