package com.rigers.db;

// Generated 24-mar-2014 14.44.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Edificio generated by hbm2java
 */
public class Edificio implements java.io.Serializable {

	private int idEdificio;
	private Compartimento compartimento;
	private String indirizzoEdificio;
	private Set dispositivos = new HashSet(0);

	public Edificio() {
	}

	public Edificio(int idEdificio, Compartimento compartimento) {
		this.idEdificio = idEdificio;
		this.compartimento = compartimento;
	}

	public Edificio(int idEdificio, Compartimento compartimento,
			String indirizzoEdificio, Set dispositivos) {
		this.idEdificio = idEdificio;
		this.compartimento = compartimento;
		this.indirizzoEdificio = indirizzoEdificio;
		this.dispositivos = dispositivos;
	}

	public int getIdEdificio() {
		return this.idEdificio;
	}

	public void setIdEdificio(int idEdificio) {
		this.idEdificio = idEdificio;
	}

	public Compartimento getCompartimento() {
		return this.compartimento;
	}

	public void setCompartimento(Compartimento compartimento) {
		this.compartimento = compartimento;
	}

	public String getIndirizzoEdificio() {
		return this.indirizzoEdificio;
	}

	public void setIndirizzoEdificio(String indirizzoEdificio) {
		this.indirizzoEdificio = indirizzoEdificio;
	}

	public Set getDispositivos() {
		return this.dispositivos;
	}

	public void setDispositivos(Set dispositivos) {
		this.dispositivos = dispositivos;
	}

}
