package com.rigers.db;

// Generated 24-mar-2014 14.44.56 by Hibernate Tools 3.4.0.CR1

/**
 * IlluminazionePub generated by hbm2java
 */
public class IlluminazionePub implements java.io.Serializable {

	private IlluminazionePubId id;
	private DispositivoPub dispositivoPub;
	private String nomeDispositivoPub;
	private Telecontrollo telecontrollo;
	private AllarmiStatoImpianto allarmiStatoImpianto;
	private ParametriElettrici parametriElettrici;

	public IlluminazionePub() {
	}

	public IlluminazionePub(DispositivoPub dispositivoPub) {
		this.dispositivoPub = dispositivoPub;
	}

	public IlluminazionePub(DispositivoPub dispositivoPub,
			String nomeDispositivoPub, Telecontrollo telecontrollo,
			AllarmiStatoImpianto allarmiStatoImpianto,
			ParametriElettrici parametriElettrici) {
		this.dispositivoPub = dispositivoPub;
		this.nomeDispositivoPub = nomeDispositivoPub;
		this.telecontrollo = telecontrollo;
		this.allarmiStatoImpianto = allarmiStatoImpianto;
		this.parametriElettrici = parametriElettrici;
	}

	public IlluminazionePubId getId() {
		return this.id;
	}

	public void setId(IlluminazionePubId id) {
		this.id = id;
	}

	public DispositivoPub getDispositivoPub() {
		return this.dispositivoPub;
	}

	public void setDispositivoPub(DispositivoPub dispositivoPub) {
		this.dispositivoPub = dispositivoPub;
	}

	public String getNomeDispositivoPub() {
		return this.nomeDispositivoPub;
	}

	public void setNomeDispositivoPub(String nomeDispositivoPub) {
		this.nomeDispositivoPub = nomeDispositivoPub;
	}

	public Telecontrollo getTelecontrollo() {
		return this.telecontrollo;
	}

	public void setTelecontrollo(Telecontrollo telecontrollo) {
		this.telecontrollo = telecontrollo;
	}

	public AllarmiStatoImpianto getAllarmiStatoImpianto() {
		return this.allarmiStatoImpianto;
	}

	public void setAllarmiStatoImpianto(
			AllarmiStatoImpianto allarmiStatoImpianto) {
		this.allarmiStatoImpianto = allarmiStatoImpianto;
	}

	public ParametriElettrici getParametriElettrici() {
		return this.parametriElettrici;
	}

	public void setParametriElettrici(ParametriElettrici parametriElettrici) {
		this.parametriElettrici = parametriElettrici;
	}

}
