package com.rigers.db;

// Generated 27-mar-2014 21.08.14 by Hibernate Tools 3.4.0.CR1

/**
 * LetturaDispositivo generated by hbm2java
 */
public class LetturaDispositivo implements java.io.Serializable {

	private LetturaDispositivoId id;
	private Dispositivo dispositivo;
	private MeterGas meterGas;
	private MeterSonde meterSonde;
	private MeterAcqua meterAcqua;
	private MeterElettrico meterElettrico;
	private MeterRipartitoreCalore meterRipartitoreCalore;
	private MeterTermie meterTermie;

	public LetturaDispositivo() {
	}

	public LetturaDispositivo(LetturaDispositivoId id, Dispositivo dispositivo) {
		this.id = id;
		this.dispositivo = dispositivo;
	}

	public LetturaDispositivo(LetturaDispositivoId id, Dispositivo dispositivo,
			MeterGas meterGas, MeterSonde meterSonde, MeterAcqua meterAcqua,
			MeterElettrico meterElettrico,
			MeterRipartitoreCalore meterRipartitoreCalore,
			MeterTermie meterTermie) {
		this.id = id;
		this.dispositivo = dispositivo;
		this.meterGas = meterGas;
		this.meterSonde = meterSonde;
		this.meterAcqua = meterAcqua;
		this.meterElettrico = meterElettrico;
		this.meterRipartitoreCalore = meterRipartitoreCalore;
		this.meterTermie = meterTermie;
	}

	public LetturaDispositivoId getId() {
		return this.id;
	}

	public void setId(LetturaDispositivoId id) {
		this.id = id;
	}

	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	public MeterGas getMeterGas() {
		return this.meterGas;
	}

	public void setMeterGas(MeterGas meterGas) {
		this.meterGas = meterGas;
	}

	public MeterSonde getMeterSonde() {
		return this.meterSonde;
	}

	public void setMeterSonde(MeterSonde meterSonde) {
		this.meterSonde = meterSonde;
	}

	public MeterAcqua getMeterAcqua() {
		return this.meterAcqua;
	}

	public void setMeterAcqua(MeterAcqua meterAcqua) {
		this.meterAcqua = meterAcqua;
	}

	public MeterElettrico getMeterElettrico() {
		return this.meterElettrico;
	}

	public void setMeterElettrico(MeterElettrico meterElettrico) {
		this.meterElettrico = meterElettrico;
	}

	public MeterRipartitoreCalore getMeterRipartitoreCalore() {
		return this.meterRipartitoreCalore;
	}

	public void setMeterRipartitoreCalore(
			MeterRipartitoreCalore meterRipartitoreCalore) {
		this.meterRipartitoreCalore = meterRipartitoreCalore;
	}

	public MeterTermie getMeterTermie() {
		return this.meterTermie;
	}

	public void setMeterTermie(MeterTermie meterTermie) {
		this.meterTermie = meterTermie;
	}

}
