package com.rigers.db;

// Generated 27-mar-2014 21.08.14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * LetturaDispositivoPub generated by hbm2java
 */
public class LetturaDispositivoPub implements java.io.Serializable {

	private LetturaDispositivoPubId id;
	private DispositivoPub dispositivoPub;
	private Telecontrollo telecontrollo;
	private ParametriElettrici parametriElettrici;
	private Set videosorveglianzas = new HashSet(0);
	private AllarmiStatoImpianto allarmiStatoImpianto;

	public LetturaDispositivoPub() {
	}

	public LetturaDispositivoPub(LetturaDispositivoPubId id,
			DispositivoPub dispositivoPub) {
		this.id = id;
		this.dispositivoPub = dispositivoPub;
	}

	public LetturaDispositivoPub(LetturaDispositivoPubId id,
			DispositivoPub dispositivoPub, Telecontrollo telecontrollo,
			ParametriElettrici parametriElettrici, Set videosorveglianzas,
			AllarmiStatoImpianto allarmiStatoImpianto) {
		this.id = id;
		this.dispositivoPub = dispositivoPub;
		this.telecontrollo = telecontrollo;
		this.parametriElettrici = parametriElettrici;
		this.videosorveglianzas = videosorveglianzas;
		this.allarmiStatoImpianto = allarmiStatoImpianto;
	}

	public LetturaDispositivoPubId getId() {
		return this.id;
	}

	public void setId(LetturaDispositivoPubId id) {
		this.id = id;
	}

	public DispositivoPub getDispositivoPub() {
		return this.dispositivoPub;
	}

	public void setDispositivoPub(DispositivoPub dispositivoPub) {
		this.dispositivoPub = dispositivoPub;
	}

	public Telecontrollo getTelecontrollo() {
		return this.telecontrollo;
	}

	public void setTelecontrollo(Telecontrollo telecontrollo) {
		this.telecontrollo = telecontrollo;
	}

	public ParametriElettrici getParametriElettrici() {
		return this.parametriElettrici;
	}

	public void setParametriElettrici(ParametriElettrici parametriElettrici) {
		this.parametriElettrici = parametriElettrici;
	}

	public Set getVideosorveglianzas() {
		return this.videosorveglianzas;
	}

	public void setVideosorveglianzas(Set videosorveglianzas) {
		this.videosorveglianzas = videosorveglianzas;
	}

	public AllarmiStatoImpianto getAllarmiStatoImpianto() {
		return this.allarmiStatoImpianto;
	}

	public void setAllarmiStatoImpianto(
			AllarmiStatoImpianto allarmiStatoImpianto) {
		this.allarmiStatoImpianto = allarmiStatoImpianto;
	}

}
