package com.rigers.db;

// Generated 24-mar-2014 14.44.56 by Hibernate Tools 3.4.0.CR1

/**
 * LetturaDispositivoPub generated by hbm2java
 */
public class LetturaDispositivoPub implements java.io.Serializable {

	private LetturaDispositivoPubId id;
	private DispositivoPub dispositivoPub;

	public LetturaDispositivoPub() {
	}

	public LetturaDispositivoPub(LetturaDispositivoPubId id,
			DispositivoPub dispositivoPub) {
		this.id = id;
		this.dispositivoPub = dispositivoPub;
	}

	public LetturaDispositivoPubId getId() {
		return this.id;
	}

	public void setId(LetturaDispositivoPubId id) {
		this.id = id;
	}

	public DispositivoPub getDispositivoPub() {
		return this.dispositivoPub;
	}

	public void setDispositivoPub(DispositivoPub dispositivoPub) {
		this.dispositivoPub = dispositivoPub;
	}

}
