package com.rigers.db;

// Generated 24-mar-2014 14.44.56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LetturaDispositivoId generated by hbm2java
 */
public class LetturaDispositivoId implements java.io.Serializable {

	private int idDispositivo;
	private int idEdificio;
	private Date dataLettura;

	public LetturaDispositivoId() {
	}

	public LetturaDispositivoId(int idDispositivo, int idEdificio,
			Date dataLettura) {
		this.idDispositivo = idDispositivo;
		this.idEdificio = idEdificio;
		this.dataLettura = dataLettura;
	}

	public int getIdDispositivo() {
		return this.idDispositivo;
	}

	public void setIdDispositivo(int idDispositivo) {
		this.idDispositivo = idDispositivo;
	}

	public int getIdEdificio() {
		return this.idEdificio;
	}

	public void setIdEdificio(int idEdificio) {
		this.idEdificio = idEdificio;
	}

	public Date getDataLettura() {
		return this.dataLettura;
	}

	public void setDataLettura(Date dataLettura) {
		this.dataLettura = dataLettura;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LetturaDispositivoId))
			return false;
		LetturaDispositivoId castOther = (LetturaDispositivoId) other;

		return (this.getIdDispositivo() == castOther.getIdDispositivo())
				&& (this.getIdEdificio() == castOther.getIdEdificio())
				&& ((this.getDataLettura() == castOther.getDataLettura()) || (this
						.getDataLettura() != null
						&& castOther.getDataLettura() != null && this
						.getDataLettura().equals(castOther.getDataLettura())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDispositivo();
		result = 37 * result + this.getIdEdificio();
		result = 37
				* result
				+ (getDataLettura() == null ? 0 : this.getDataLettura()
						.hashCode());
		return result;
	}

}
