package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LetturaDispositivoPub generated by hbm2java
 */
public class LetturaDispositivoPub implements java.io.Serializable {

	private int idLetturaPub;
	private DispositivoPub dispositivoPub;
	private Date dataLetturaPub;

	public LetturaDispositivoPub() {
	}

	public LetturaDispositivoPub(int idLetturaPub,
			DispositivoPub dispositivoPub, Date dataLetturaPub) {
		this.idLetturaPub = idLetturaPub;
		this.dispositivoPub = dispositivoPub;
		this.dataLetturaPub = dataLetturaPub;
	}

	public int getIdLetturaPub() {
		return this.idLetturaPub;
	}

	public void setIdLetturaPub(int idLetturaPub) {
		this.idLetturaPub = idLetturaPub;
	}

	public DispositivoPub getDispositivoPub() {
		return this.dispositivoPub;
	}

	public void setDispositivoPub(DispositivoPub dispositivoPub) {
		this.dispositivoPub = dispositivoPub;
	}

	public Date getDataLetturaPub() {
		return this.dataLetturaPub;
	}

	public void setDataLetturaPub(Date dataLetturaPub) {
		this.dataLetturaPub = dataLetturaPub;
	}

}
