package com.rigers.db;

// Generated 7-apr-2014 11.05.46 by Hibernate Tools 3.4.0.CR1

/**
 * MeterRipartitoreCalore generated by hbm2java
 */
public class MeterRipartitoreCalore implements java.io.Serializable {

	private MeterRipartitoreCaloreId id;
	private LetturaDispositivo letturaDispositivo;
	private Integer unitaConsumo;

	public MeterRipartitoreCalore() {
	}

	public MeterRipartitoreCalore(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public MeterRipartitoreCalore(LetturaDispositivo letturaDispositivo,
			Integer unitaConsumo) {
		this.letturaDispositivo = letturaDispositivo;
		this.unitaConsumo = unitaConsumo;
	}

	public MeterRipartitoreCaloreId getId() {
		return this.id;
	}

	public void setId(MeterRipartitoreCaloreId id) {
		this.id = id;
	}

	public LetturaDispositivo getLetturaDispositivo() {
		return this.letturaDispositivo;
	}

	public void setLetturaDispositivo(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public Integer getUnitaConsumo() {
		return this.unitaConsumo;
	}

	public void setUnitaConsumo(Integer unitaConsumo) {
		this.unitaConsumo = unitaConsumo;
	}

}
