package com.rigers.db;

// Generated 24-mar-2014 14.44.56 by Hibernate Tools 3.4.0.CR1

/**
 * MeterSonde generated by hbm2java
 */
public class MeterSonde implements java.io.Serializable {

	private MeterSondeId id;
	private Dispositivo dispositivo;
	private Integer tempLocali;
	private Integer tempEsterna;
	private Integer tempGiorno;
	private Integer luminosita;
	private Integer solarimetro;
	private Integer sismografo;

	public MeterSonde() {
	}

	public MeterSonde(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	public MeterSonde(Dispositivo dispositivo, Integer tempLocali,
			Integer tempEsterna, Integer tempGiorno, Integer luminosita,
			Integer solarimetro, Integer sismografo) {
		this.dispositivo = dispositivo;
		this.tempLocali = tempLocali;
		this.tempEsterna = tempEsterna;
		this.tempGiorno = tempGiorno;
		this.luminosita = luminosita;
		this.solarimetro = solarimetro;
		this.sismografo = sismografo;
	}

	public MeterSondeId getId() {
		return this.id;
	}

	public void setId(MeterSondeId id) {
		this.id = id;
	}

	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	public Integer getTempLocali() {
		return this.tempLocali;
	}

	public void setTempLocali(Integer tempLocali) {
		this.tempLocali = tempLocali;
	}

	public Integer getTempEsterna() {
		return this.tempEsterna;
	}

	public void setTempEsterna(Integer tempEsterna) {
		this.tempEsterna = tempEsterna;
	}

	public Integer getTempGiorno() {
		return this.tempGiorno;
	}

	public void setTempGiorno(Integer tempGiorno) {
		this.tempGiorno = tempGiorno;
	}

	public Integer getLuminosita() {
		return this.luminosita;
	}

	public void setLuminosita(Integer luminosita) {
		this.luminosita = luminosita;
	}

	public Integer getSolarimetro() {
		return this.solarimetro;
	}

	public void setSolarimetro(Integer solarimetro) {
		this.solarimetro = solarimetro;
	}

	public Integer getSismografo() {
		return this.sismografo;
	}

	public void setSismografo(Integer sismografo) {
		this.sismografo = sismografo;
	}

}
