package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * MeterSonde generated by hbm2java
 */
public class MeterSonde implements java.io.Serializable {

	private int idLettura;
	private LetturaDispositivo letturaDispositivo;
	private Integer tempLocali;
	private Integer tempEsterna;
	private Integer tempGiorno;
	private Integer luminosita;
	private Integer solarimetro;
	private Integer sismografo;

	public MeterSonde() {
	}

	public MeterSonde(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public MeterSonde(LetturaDispositivo letturaDispositivo,
			Integer tempLocali, Integer tempEsterna, Integer tempGiorno,
			Integer luminosita, Integer solarimetro, Integer sismografo) {
		this.letturaDispositivo = letturaDispositivo;
		this.tempLocali = tempLocali;
		this.tempEsterna = tempEsterna;
		this.tempGiorno = tempGiorno;
		this.luminosita = luminosita;
		this.solarimetro = solarimetro;
		this.sismografo = sismografo;
	}

	public int getIdLettura() {
		return this.idLettura;
	}

	public void setIdLettura(int idLettura) {
		this.idLettura = idLettura;
	}

	public LetturaDispositivo getLetturaDispositivo() {
		return this.letturaDispositivo;
	}

	public void setLetturaDispositivo(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public Integer getTempLocali() {
		return this.tempLocali;
	}

	public void setTempLocali(Integer tempLocali) {
		this.tempLocali = tempLocali;
	}

	public Integer getTempEsterna() {
		return this.tempEsterna;
	}

	public void setTempEsterna(Integer tempEsterna) {
		this.tempEsterna = tempEsterna;
	}

	public Integer getTempGiorno() {
		return this.tempGiorno;
	}

	public void setTempGiorno(Integer tempGiorno) {
		this.tempGiorno = tempGiorno;
	}

	public Integer getLuminosita() {
		return this.luminosita;
	}

	public void setLuminosita(Integer luminosita) {
		this.luminosita = luminosita;
	}

	public Integer getSolarimetro() {
		return this.solarimetro;
	}

	public void setSolarimetro(Integer solarimetro) {
		this.solarimetro = solarimetro;
	}

	public Integer getSismografo() {
		return this.sismografo;
	}

	public void setSismografo(Integer sismografo) {
		this.sismografo = sismografo;
	}

}
