package com.rigers.db;

// Generated 27-mar-2014 21.08.14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MeterGasId generated by hbm2java
 */
public class MeterGasId implements java.io.Serializable {

	private Date dataLettura;
	private int idDispositivo;
	private int idEdificio;

	public MeterGasId() {
	}

	public MeterGasId(Date dataLettura, int idDispositivo, int idEdificio) {
		this.dataLettura = dataLettura;
		this.idDispositivo = idDispositivo;
		this.idEdificio = idEdificio;
	}

	public Date getDataLettura() {
		return this.dataLettura;
	}

	public void setDataLettura(Date dataLettura) {
		this.dataLettura = dataLettura;
	}

	public int getIdDispositivo() {
		return this.idDispositivo;
	}

	public void setIdDispositivo(int idDispositivo) {
		this.idDispositivo = idDispositivo;
	}

	public int getIdEdificio() {
		return this.idEdificio;
	}

	public void setIdEdificio(int idEdificio) {
		this.idEdificio = idEdificio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MeterGasId))
			return false;
		MeterGasId castOther = (MeterGasId) other;

		return ((this.getDataLettura() == castOther.getDataLettura()) || (this
				.getDataLettura() != null && castOther.getDataLettura() != null && this
				.getDataLettura().equals(castOther.getDataLettura())))
				&& (this.getIdDispositivo() == castOther.getIdDispositivo())
				&& (this.getIdEdificio() == castOther.getIdEdificio());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDataLettura() == null ? 0 : this.getDataLettura()
						.hashCode());
		result = 37 * result + this.getIdDispositivo();
		result = 37 * result + this.getIdEdificio();
		return result;
	}

}
