package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * MeterRipartitoreCalore generated by hbm2java
 */
public class MeterRipartitoreCalore implements java.io.Serializable {

	private int idLettura;
	private LetturaDispositivo letturaDispositivo;
	private Integer unitaConsumo;

	public MeterRipartitoreCalore() {
	}

	public MeterRipartitoreCalore(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public MeterRipartitoreCalore(LetturaDispositivo letturaDispositivo,
			Integer unitaConsumo) {
		this.letturaDispositivo = letturaDispositivo;
		this.unitaConsumo = unitaConsumo;
	}

	public int getIdLettura() {
		return this.idLettura;
	}

	public void setIdLettura(int idLettura) {
		this.idLettura = idLettura;
	}

	public LetturaDispositivo getLetturaDispositivo() {
		return this.letturaDispositivo;
	}

	public void setLetturaDispositivo(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public Integer getUnitaConsumo() {
		return this.unitaConsumo;
	}

	public void setUnitaConsumo(Integer unitaConsumo) {
		this.unitaConsumo = unitaConsumo;
	}

}
