package com.rigers.db;

// Generated 7-apr-2014 11.05.46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MeterAcqua generated by hbm2java
 */
public class MeterAcqua implements java.io.Serializable {

	private MeterAcquaId id;
	private LetturaDispositivo letturaDispositivo;
	private Integer currentReadoutValue;
	private Integer periodicReadoutValue;
	private Date periodicReadingDate;

	public MeterAcqua() {
	}

	public MeterAcqua(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public MeterAcqua(LetturaDispositivo letturaDispositivo,
			Integer currentReadoutValue, Integer periodicReadoutValue,
			Date periodicReadingDate) {
		this.letturaDispositivo = letturaDispositivo;
		this.currentReadoutValue = currentReadoutValue;
		this.periodicReadoutValue = periodicReadoutValue;
		this.periodicReadingDate = periodicReadingDate;
	}

	public MeterAcquaId getId() {
		return this.id;
	}

	public void setId(MeterAcquaId id) {
		this.id = id;
	}

	public LetturaDispositivo getLetturaDispositivo() {
		return this.letturaDispositivo;
	}

	public void setLetturaDispositivo(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public Integer getCurrentReadoutValue() {
		return this.currentReadoutValue;
	}

	public void setCurrentReadoutValue(Integer currentReadoutValue) {
		this.currentReadoutValue = currentReadoutValue;
	}

	public Integer getPeriodicReadoutValue() {
		return this.periodicReadoutValue;
	}

	public void setPeriodicReadoutValue(Integer periodicReadoutValue) {
		this.periodicReadoutValue = periodicReadoutValue;
	}

	public Date getPeriodicReadingDate() {
		return this.periodicReadingDate;
	}

	public void setPeriodicReadingDate(Date periodicReadingDate) {
		this.periodicReadingDate = periodicReadingDate;
	}

}
