package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MeterGas generated by hbm2java
 */
public class MeterGas implements java.io.Serializable {

	private int idLettura;
	private LetturaDispositivo letturaDispositivo;
	private Byte pm1NetworkStatus;
	private Byte statoValvola;
	private Byte comandoValvola;
	private Date unixTimeEogd;
	private String dailyDiagnostic;
	private Integer totVbEogdF1;
	private Integer totVbEogdF2;
	private Integer totVbEogdF3;
	private Integer totVaEogd;
	private Integer qbcMax;
	private Date qbcMaxTimestamp;

	public MeterGas() {
	}

	public MeterGas(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public MeterGas(LetturaDispositivo letturaDispositivo,
			Byte pm1NetworkStatus, Byte statoValvola, Byte comandoValvola,
			Date unixTimeEogd, String dailyDiagnostic, Integer totVbEogdF1,
			Integer totVbEogdF2, Integer totVbEogdF3, Integer totVaEogd,
			Integer qbcMax, Date qbcMaxTimestamp) {
		this.letturaDispositivo = letturaDispositivo;
		this.pm1NetworkStatus = pm1NetworkStatus;
		this.statoValvola = statoValvola;
		this.comandoValvola = comandoValvola;
		this.unixTimeEogd = unixTimeEogd;
		this.dailyDiagnostic = dailyDiagnostic;
		this.totVbEogdF1 = totVbEogdF1;
		this.totVbEogdF2 = totVbEogdF2;
		this.totVbEogdF3 = totVbEogdF3;
		this.totVaEogd = totVaEogd;
		this.qbcMax = qbcMax;
		this.qbcMaxTimestamp = qbcMaxTimestamp;
	}

	public int getIdLettura() {
		return this.idLettura;
	}

	public void setIdLettura(int idLettura) {
		this.idLettura = idLettura;
	}

	public LetturaDispositivo getLetturaDispositivo() {
		return this.letturaDispositivo;
	}

	public void setLetturaDispositivo(LetturaDispositivo letturaDispositivo) {
		this.letturaDispositivo = letturaDispositivo;
	}

	public Byte getPm1NetworkStatus() {
		return this.pm1NetworkStatus;
	}

	public void setPm1NetworkStatus(Byte pm1NetworkStatus) {
		this.pm1NetworkStatus = pm1NetworkStatus;
	}

	public Byte getStatoValvola() {
		return this.statoValvola;
	}

	public void setStatoValvola(Byte statoValvola) {
		this.statoValvola = statoValvola;
	}

	public Byte getComandoValvola() {
		return this.comandoValvola;
	}

	public void setComandoValvola(Byte comandoValvola) {
		this.comandoValvola = comandoValvola;
	}

	public Date getUnixTimeEogd() {
		return this.unixTimeEogd;
	}

	public void setUnixTimeEogd(Date unixTimeEogd) {
		this.unixTimeEogd = unixTimeEogd;
	}

	public String getDailyDiagnostic() {
		return this.dailyDiagnostic;
	}

	public void setDailyDiagnostic(String dailyDiagnostic) {
		this.dailyDiagnostic = dailyDiagnostic;
	}

	public Integer getTotVbEogdF1() {
		return this.totVbEogdF1;
	}

	public void setTotVbEogdF1(Integer totVbEogdF1) {
		this.totVbEogdF1 = totVbEogdF1;
	}

	public Integer getTotVbEogdF2() {
		return this.totVbEogdF2;
	}

	public void setTotVbEogdF2(Integer totVbEogdF2) {
		this.totVbEogdF2 = totVbEogdF2;
	}

	public Integer getTotVbEogdF3() {
		return this.totVbEogdF3;
	}

	public void setTotVbEogdF3(Integer totVbEogdF3) {
		this.totVbEogdF3 = totVbEogdF3;
	}

	public Integer getTotVaEogd() {
		return this.totVaEogd;
	}

	public void setTotVaEogd(Integer totVaEogd) {
		this.totVaEogd = totVaEogd;
	}

	public Integer getQbcMax() {
		return this.qbcMax;
	}

	public void setQbcMax(Integer qbcMax) {
		this.qbcMax = qbcMax;
	}

	public Date getQbcMaxTimestamp() {
		return this.qbcMaxTimestamp;
	}

	public void setQbcMaxTimestamp(Date qbcMaxTimestamp) {
		this.qbcMaxTimestamp = qbcMaxTimestamp;
	}

}
