package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * ParametriElettrici generated by hbm2java
 */
public class ParametriElettrici implements java.io.Serializable {

	private ParametriElettriciId id;

	public ParametriElettrici() {
	}

	public ParametriElettrici(ParametriElettriciId id) {
		this.id = id;
	}

	public ParametriElettriciId getId() {
		return this.id;
	}

	public void setId(ParametriElettriciId id) {
		this.id = id;
	}

}
