package com.rigers.db;

// Generated 27-mar-2014 21.08.14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TelecontrolloId generated by hbm2java
 */
public class TelecontrolloId implements java.io.Serializable {

	private Date dataLetturaPub;
	private int idDispositivoPub;
	private int idCompartimento;

	public TelecontrolloId() {
	}

	public TelecontrolloId(Date dataLetturaPub, int idDispositivoPub,
			int idCompartimento) {
		this.dataLetturaPub = dataLetturaPub;
		this.idDispositivoPub = idDispositivoPub;
		this.idCompartimento = idCompartimento;
	}

	public Date getDataLetturaPub() {
		return this.dataLetturaPub;
	}

	public void setDataLetturaPub(Date dataLetturaPub) {
		this.dataLetturaPub = dataLetturaPub;
	}

	public int getIdDispositivoPub() {
		return this.idDispositivoPub;
	}

	public void setIdDispositivoPub(int idDispositivoPub) {
		this.idDispositivoPub = idDispositivoPub;
	}

	public int getIdCompartimento() {
		return this.idCompartimento;
	}

	public void setIdCompartimento(int idCompartimento) {
		this.idCompartimento = idCompartimento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelecontrolloId))
			return false;
		TelecontrolloId castOther = (TelecontrolloId) other;

		return ((this.getDataLetturaPub() == castOther.getDataLetturaPub()) || (this
				.getDataLetturaPub() != null
				&& castOther.getDataLetturaPub() != null && this
				.getDataLetturaPub().equals(castOther.getDataLetturaPub())))
				&& (this.getIdDispositivoPub() == castOther
						.getIdDispositivoPub())
				&& (this.getIdCompartimento() == castOther.getIdCompartimento());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDataLetturaPub() == null ? 0 : this.getDataLetturaPub()
						.hashCode());
		result = 37 * result + this.getIdDispositivoPub();
		result = 37 * result + this.getIdCompartimento();
		return result;
	}

}
