package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * TelecontrolloId generated by hbm2java
 */
public class TelecontrolloId implements java.io.Serializable {

	private Integer programmOrarioFunzionamento;
	private Byte comandoInterruttoreMagnetotermico;
	private Byte comandoAperturaDifferenziale;
	private Byte comandoOnOffManuale;
	private Byte dimmerizzazioneOnOff;
	private Integer setPointDimmer;

	public TelecontrolloId() {
	}

	public TelecontrolloId(Integer programmOrarioFunzionamento,
			Byte comandoInterruttoreMagnetotermico,
			Byte comandoAperturaDifferenziale, Byte comandoOnOffManuale,
			Byte dimmerizzazioneOnOff, Integer setPointDimmer) {
		this.programmOrarioFunzionamento = programmOrarioFunzionamento;
		this.comandoInterruttoreMagnetotermico = comandoInterruttoreMagnetotermico;
		this.comandoAperturaDifferenziale = comandoAperturaDifferenziale;
		this.comandoOnOffManuale = comandoOnOffManuale;
		this.dimmerizzazioneOnOff = dimmerizzazioneOnOff;
		this.setPointDimmer = setPointDimmer;
	}

	public Integer getProgrammOrarioFunzionamento() {
		return this.programmOrarioFunzionamento;
	}

	public void setProgrammOrarioFunzionamento(
			Integer programmOrarioFunzionamento) {
		this.programmOrarioFunzionamento = programmOrarioFunzionamento;
	}

	public Byte getComandoInterruttoreMagnetotermico() {
		return this.comandoInterruttoreMagnetotermico;
	}

	public void setComandoInterruttoreMagnetotermico(
			Byte comandoInterruttoreMagnetotermico) {
		this.comandoInterruttoreMagnetotermico = comandoInterruttoreMagnetotermico;
	}

	public Byte getComandoAperturaDifferenziale() {
		return this.comandoAperturaDifferenziale;
	}

	public void setComandoAperturaDifferenziale(
			Byte comandoAperturaDifferenziale) {
		this.comandoAperturaDifferenziale = comandoAperturaDifferenziale;
	}

	public Byte getComandoOnOffManuale() {
		return this.comandoOnOffManuale;
	}

	public void setComandoOnOffManuale(Byte comandoOnOffManuale) {
		this.comandoOnOffManuale = comandoOnOffManuale;
	}

	public Byte getDimmerizzazioneOnOff() {
		return this.dimmerizzazioneOnOff;
	}

	public void setDimmerizzazioneOnOff(Byte dimmerizzazioneOnOff) {
		this.dimmerizzazioneOnOff = dimmerizzazioneOnOff;
	}

	public Integer getSetPointDimmer() {
		return this.setPointDimmer;
	}

	public void setSetPointDimmer(Integer setPointDimmer) {
		this.setPointDimmer = setPointDimmer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelecontrolloId))
			return false;
		TelecontrolloId castOther = (TelecontrolloId) other;

		return ((this.getProgrammOrarioFunzionamento() == castOther
				.getProgrammOrarioFunzionamento()) || (this
				.getProgrammOrarioFunzionamento() != null
				&& castOther.getProgrammOrarioFunzionamento() != null && this
				.getProgrammOrarioFunzionamento().equals(
						castOther.getProgrammOrarioFunzionamento())))
				&& ((this.getComandoInterruttoreMagnetotermico() == castOther
						.getComandoInterruttoreMagnetotermico()) || (this
						.getComandoInterruttoreMagnetotermico() != null
						&& castOther.getComandoInterruttoreMagnetotermico() != null && this
						.getComandoInterruttoreMagnetotermico()
						.equals(castOther
								.getComandoInterruttoreMagnetotermico())))
				&& ((this.getComandoAperturaDifferenziale() == castOther
						.getComandoAperturaDifferenziale()) || (this
						.getComandoAperturaDifferenziale() != null
						&& castOther.getComandoAperturaDifferenziale() != null && this
						.getComandoAperturaDifferenziale().equals(
								castOther.getComandoAperturaDifferenziale())))
				&& ((this.getComandoOnOffManuale() == castOther
						.getComandoOnOffManuale()) || (this
						.getComandoOnOffManuale() != null
						&& castOther.getComandoOnOffManuale() != null && this
						.getComandoOnOffManuale().equals(
								castOther.getComandoOnOffManuale())))
				&& ((this.getDimmerizzazioneOnOff() == castOther
						.getDimmerizzazioneOnOff()) || (this
						.getDimmerizzazioneOnOff() != null
						&& castOther.getDimmerizzazioneOnOff() != null && this
						.getDimmerizzazioneOnOff().equals(
								castOther.getDimmerizzazioneOnOff())))
				&& ((this.getSetPointDimmer() == castOther.getSetPointDimmer()) || (this
						.getSetPointDimmer() != null
						&& castOther.getSetPointDimmer() != null && this
						.getSetPointDimmer().equals(
								castOther.getSetPointDimmer())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProgrammOrarioFunzionamento() == null ? 0 : this
						.getProgrammOrarioFunzionamento().hashCode());
		result = 37
				* result
				+ (getComandoInterruttoreMagnetotermico() == null ? 0 : this
						.getComandoInterruttoreMagnetotermico().hashCode());
		result = 37
				* result
				+ (getComandoAperturaDifferenziale() == null ? 0 : this
						.getComandoAperturaDifferenziale().hashCode());
		result = 37
				* result
				+ (getComandoOnOffManuale() == null ? 0 : this
						.getComandoOnOffManuale().hashCode());
		result = 37
				* result
				+ (getDimmerizzazioneOnOff() == null ? 0 : this
						.getDimmerizzazioneOnOff().hashCode());
		result = 37
				* result
				+ (getSetPointDimmer() == null ? 0 : this.getSetPointDimmer()
						.hashCode());
		return result;
	}

}
