package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * Telecontrollo generated by hbm2java
 */
public class Telecontrollo implements java.io.Serializable {

	private TelecontrolloId id;

	public Telecontrollo() {
	}

	public Telecontrollo(TelecontrolloId id) {
		this.id = id;
	}

	public TelecontrolloId getId() {
		return this.id;
	}

	public void setId(TelecontrolloId id) {
		this.id = id;
	}

}
