package com.rigers.db;

// Generated 9-apr-2014 10.10.47 by Hibernate Tools 3.4.0.CR1

/**
 * Videosorveglianza generated by hbm2java
 */
public class Videosorveglianza implements java.io.Serializable {

	private int idVideosorveglianza;

	public Videosorveglianza() {
	}

	public Videosorveglianza(int idVideosorveglianza) {
		this.idVideosorveglianza = idVideosorveglianza;
	}

	public int getIdVideosorveglianza() {
		return this.idVideosorveglianza;
	}

	public void setIdVideosorveglianza(int idVideosorveglianza) {
		this.idVideosorveglianza = idVideosorveglianza;
	}

}
