package com.rigers.db;

// Generated 7-apr-2014 11.05.46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VideosorveglianzaId generated by hbm2java
 */
public class VideosorveglianzaId implements java.io.Serializable {

	private int idVideosorveglianza;
	private Date dataLetturaPub;
	private int idDispositivoPub;
	private int idCompartimento;

	public VideosorveglianzaId() {
	}

	public VideosorveglianzaId(int idVideosorveglianza, Date dataLetturaPub,
			int idDispositivoPub, int idCompartimento) {
		this.idVideosorveglianza = idVideosorveglianza;
		this.dataLetturaPub = dataLetturaPub;
		this.idDispositivoPub = idDispositivoPub;
		this.idCompartimento = idCompartimento;
	}

	public int getIdVideosorveglianza() {
		return this.idVideosorveglianza;
	}

	public void setIdVideosorveglianza(int idVideosorveglianza) {
		this.idVideosorveglianza = idVideosorveglianza;
	}

	public Date getDataLetturaPub() {
		return this.dataLetturaPub;
	}

	public void setDataLetturaPub(Date dataLetturaPub) {
		this.dataLetturaPub = dataLetturaPub;
	}

	public int getIdDispositivoPub() {
		return this.idDispositivoPub;
	}

	public void setIdDispositivoPub(int idDispositivoPub) {
		this.idDispositivoPub = idDispositivoPub;
	}

	public int getIdCompartimento() {
		return this.idCompartimento;
	}

	public void setIdCompartimento(int idCompartimento) {
		this.idCompartimento = idCompartimento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VideosorveglianzaId))
			return false;
		VideosorveglianzaId castOther = (VideosorveglianzaId) other;

		return (this.getIdVideosorveglianza() == castOther
				.getIdVideosorveglianza())
				&& ((this.getDataLetturaPub() == castOther.getDataLetturaPub()) || (this
						.getDataLetturaPub() != null
						&& castOther.getDataLetturaPub() != null && this
						.getDataLetturaPub().equals(
								castOther.getDataLetturaPub())))
				&& (this.getIdDispositivoPub() == castOther
						.getIdDispositivoPub())
				&& (this.getIdCompartimento() == castOther.getIdCompartimento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVideosorveglianza();
		result = 37
				* result
				+ (getDataLetturaPub() == null ? 0 : this.getDataLetturaPub()
						.hashCode());
		result = 37 * result + this.getIdDispositivoPub();
		result = 37 * result + this.getIdCompartimento();
		return result;
	}

}
