package com.rigers.db;

// Generated 7-apr-2014 11.05.46 by Hibernate Tools 3.4.0.CR1

/**
 * Videosorveglianza generated by hbm2java
 */
public class Videosorveglianza implements java.io.Serializable {

	private VideosorveglianzaId id;
	private LetturaDispositivoPub letturaDispositivoPub;

	public Videosorveglianza() {
	}

	public Videosorveglianza(VideosorveglianzaId id,
			LetturaDispositivoPub letturaDispositivoPub) {
		this.id = id;
		this.letturaDispositivoPub = letturaDispositivoPub;
	}

	public VideosorveglianzaId getId() {
		return this.id;
	}

	public void setId(VideosorveglianzaId id) {
		this.id = id;
	}

	public LetturaDispositivoPub getLetturaDispositivoPub() {
		return this.letturaDispositivoPub;
	}

	public void setLetturaDispositivoPub(
			LetturaDispositivoPub letturaDispositivoPub) {
		this.letturaDispositivoPub = letturaDispositivoPub;
	}

}
